msiexec /i "SOLUS3AgentInstaller_x64.msi" AGENTSERVICEADDRESS=net.tcp://localhost:52966 DEPLOYMENTSERVERADDRESS=net.tcp://SIMS-SERVER:52965 RSAKEYPATH="D:\Solus3\Key\" PREDEFINEDAGENTTARGETS="SIMS" /qr

timeout /t 10